version: '3.9'

services:
  web:
    build: .
    container_name: fastapi_app
    env_file:
      - .env
    expose:
      - "80"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./templates:/var/www/templates
    depends_on:
      - web
    restart: unless-stopped
